name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'supabase/**'

jobs:
  deploy:
    name: Deploy to Supabase
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
  
      - run: supabase functions deploy --project-ref $PROJECT_ID